const routes = [
  {
    path: "/home",
    name: "Inicio",
    component: "HomePage",
    isAuth: false,
    view: true,
  },
  {
    path: "/marketplace",
    name: "Tienda",
    component: "MarketPage",
    isAuth: false,
    view: true,
  },
  {
    path: "/planning/:id",
    name: "Tienda",
    component: "PlanningDetailPage",
    isAuth: false,
    view: false,
  },
  {
    path: "/contact",
    name: "Contacto",
    component: "ContactPage",
    isAuth: false,
    view: true,
  },
  {
    path: "/profile",
    name: "Perfil",
    component: "ProfilePage",
    isAuth: true,
    view: false,
  },
  {
    path: "/profile/public/:id",
    name: "ProfilePublic",
    component: "ProfilePublicPage",
    isAuth: true,
    view: false,
  },
  {
    path: "/subscriptions",
    name: "ProfilePublic",
    component: "SubscriptionListPage",
    isAuth: true,
    view: false,
  },
  {
    path: "/subscriptions/:id",
    name: "ProfilePublic",
    component: "SubscriptionDetailPage",
    isAuth: true,
    view: false,
  },
  {
    path: "/login",
    name: "Login",
    component: "LoginPage",
    isAuth: false,
    view: false,
  },
  {
    path: "/register",
    name: "Register",
    component: "RegisterPage",
    isAuth: false,
    view: false,
  },
  {
    path: "/chats",
    name: "Chats",
    component: "ChatListPage",
    isAuth: true,
    view: true,
  },
  {
    path: "/chat/:chatId",
    name: "Chats",
    component: "ChatPage",
    isAuth: true,
    view: false,
  },
  {
    path: "/admin",
    name: "Admin",
    component: "HomeAdminPage",
    isAuth: true,
    role: 1,
    view: true,
  },
  {
    path: "/admin/categories",
    name: "Admin",
    component: "CategoriesView",
    isAuth: true,
    role: 1,
    view: false,
  },
  {
    path: "/admin/payments",
    name: "Admin",
    component: "PaymentsView",
    isAuth: true,
    role: 1,
    view: false,
  },
  {
    path: "/admin/professionals",
    name: "Admin",
    component: "ProfessionalsView",
    isAuth: true,
    role: 1,
    view: false,
  },
  {
    path: "/admin/specialities",
    name: "Admin",
    component: "SpecialitiesView",
    isAuth: true,
    role: 1,
    view: false,
  },
  {
    path: "/admin/users",
    name: "Admin",
    component: "UsersView",
    isAuth: true,
    role: 1,
    view: false,
  },
  {
    path: "/professional",
    name: "Panel",
    component: "HomeProPage",
    isAuth: true,
    role: 3,
    view: true,
  },
  {
    path: "/professional/create",
    name: "Panel",
    component: "CreatePlanningPage",
    isAuth: true,
    role: 3,
    view: false,
  },
  {
    path: "/professional/edit/:id",
    name: "Panel",
    component: "EditPlanningPage",
    isAuth: true,
    role: 3,
    view: false,
  },
  {
    path: "/professional/delete/:id",
    name: "Panel",
    component: "DeletePlanningPage",
    isAuth: true,
    role: 3,
    view: false,
  },
  {
    path: "/professional/subscriptions/:id",
    name: "Panel",
    component: "SubscriptionsPage",
    isAuth: true,
    role: 3,
    view: false,
  },
  {
    path: "/professionals",
    name: "Professionales",
    component: "ProfessionalPage",
    isAuth: false,
    view: false,
  },
  {
    path: "/subscriptions",
    name: "Subscriptions",
    component: "SubscriptionListPage",
    isAuth: true,
    view: false,
  },
  {
    path: "/subscriptions/:id",
    name: "SubscriptionDetail",
    component: "SubscriptionDetailPage",
    isAuth: true,
    view: false,
  },
  {
    path: "*",
    component: "ErrorPage",
    view: false,
  },
];

export default routes;
